export {default as Main} from './Main'
export {default as NavBar} from './NavBar'
export {default as Register} from './Register'
export {default as Posts} from './Posts'
export {default as CreatePost} from './CreatePost'